# Generated by Django 4.2.2 on 2025-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="название приятной привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная  привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
        migrations.CreateModel(
            name="UsefulHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=35, verbose_name="название полезной привычки"
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=35, verbose_name="название места"),
                ),
                ("time", models.TimeField(verbose_name="время")),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        null=True,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=50, verbose_name="название действия"),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Вознаграждение за выполнение полезной привычки",
                    ),
                ),
                (
                    "sign_publicity",
                    models.BooleanField(
                        verbose_name="Публичная полезная привычка или нет"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Время на выполнение в секундах"
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
            },
        ),
    ]
