# Generated by Django 4.2.2 on 2025-05-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usefulhabit",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_useful_habit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель полезной привычки",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="pleasant_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pleasant_habit",
                to="habits.pleasanthabit",
                verbose_name="приятная привычка",
            ),
        ),
        migrations.AddField(
            model_name="pleasanthabit",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_pleasant_habit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель приятной привычки",
            ),
        ),
    ]
